### ISSUE TITLE
This no longer works on FW 11.0.0

### ISSUE THREAD

**Issue by Cylent1** [rdmrocha/linkalho#10]
Just a heads up This no longer works on FW 11.0.0

**Comment by rdmrocha** [comment]
Thanks. For now, I lack time to pick it up. Once I update my console to 11.0.0 I'll give it a look

**Comment by deejay87** [comment]
e agora em 11.0.1 ^^

**Comment by rdmrocha** [comment]
Support for 11.0.0 implemented in v1.0.4
