### ISSUE TITLE
Crash on FW 11.0.1 

### ISSUE THREAD

**Issue by zLeqitEclipse** [rdmrocha/linkalho#11]
Hi there, i have a Problem with the Software on my switch. (DeepSea 1.9.1, AMS 0.16.1, FW 11.0.1)

Everytime i do Link / Unlink, my switch crashes with the Following Error: „Failed! filesystem error: recursive directory iterator cannot open directory: No such device [account:/su]

![A5713328-A970-4B89-BB35-3D43DFC8121C](https://user-images.githubusercontent.com/57456420/102486065-c624a980-4068-11eb-93c0-089f5b96bc7f.jpeg)

**Comment by PixelBurstHD** [comment]
fixed in v1.0.4

**Comment by rdmrocha** [comment]
v1.0.4 was only tested on 11.0.0
Please retest on 11.0.1 and report back if it's fixed

**Comment by PixelBurstHD** [comment]
> v1.0.4 was only tested on 11.0.0
> @zLeqitEclipse Please retest on 11.0.1 and report back if it's fixed

Sorry should have been more clear, I tested on 11.0.1 having upgraded/reset due to a new SD card. It works great work! 👍

**Comment by PhantomThieve** [comment]
@rdmrocha It doesnt work to me at 11.0.1, same error than @zLeqitEclipse
