### ISSUE TITLE
Make fails with libnx 4.0.0

### ISSUE THREAD

**Issue by hrvylein** [rdmrocha/linkalho#14]
Make fails with latest libnx while compiling https://github.com/rdmrocha/linkalho/blob/d17ed70fe1a196b6534159a849959709c5e60ce2/src/utils.cpp#L72

Problematic line is https://github.com/rdmrocha/linkalho/blob/d17ed70fe1a196b6534159a849959709c5e60ce2/src/utils.cpp#L80

**Comment by rdmrocha** [comment]
latest master is now compiling against libnx4
