### ISSUE TITLE
Black screen on 11.0.1

### ISSUE THREAD

**Issue by darkstar** [rdmrocha/linkalho#15]
I'm getting nothing but a black screen when trying to run lincalho (both in applet mode and in full homebrew).

I'm on 11.0.1 with Atmosphere 0.16.1

**Comment by Borrajo** [comment]
the atmosphere 0.16.1 lasted less than a week. consider update atmosphere, at 0.16.2 minimally.

**Comment by darkstar** [comment]
okay, will try, might take a few days though as my SD adapter broke and I need to get a new one :-D

**Comment by Borrajo** [comment]
do you still live in the past?
if you use Hekate as bootloader, you can mount the SD directly from your switch. 
In hekate:  
_tools->USB Tools->SD card_  
and voilá! (you will need to connect your switch to PC)
**you will never have to remove your sd from the console again.**

**Comment by rdmrocha** [comment]
Tested and working on latest Atmosphere (18.0.1) with 11.0.1
Please update your system to match that. Closing as non-reproducible
