### ISSUE TITLE
after linking atmosphere crashes

### ISSUE THREAD

**Issue by Mizerka** [rdmrocha/linkalho#17]
Hey,

Might be a one off, but currently using 11.0.1 FW with Atmo 0.18.1

app detects the atmo user and profiles, proceeds to link account and briefly displays accounts linked info. Only to then crash into atmo debug screen.

I assume it's because I've swapped my reload_payload.bin to hekate but not sure.

Profiles still link as expected and confirmed with Bloodstained  that no prompts are shown and game loads as expected.

**Comment by rdmrocha** [comment]
v1.0.5 changed the way "reboot to payload" works. It now requires an explicit `reboot.bin` file in Linkalho's folder. User is responsible for providing a good known payload. Otherwise, it will trigger a regular reboot.
