### ISSUE TITLE
function question

### ISSUE THREAD

**Issue by lowburger** [rdmrocha/linkalho#19]
Hello thx for great app, I can ask exactly what it means:
"If you had any previosly linked NNID account, it will be erased!"

This means if you have official NNID link whole account will be erased, or just link? Or something else? Btw you have small typo here "previosly" = "previously"

**Comment by rdmrocha** [comment]
Thanks for the feedback. 

The rest will be replaced by "**If you had any previously linked NNID account, it will be overwritten!**"

This should make it clear
