### ISSUE TITLE
do linkalho 1.0.5 support switch os v.12.0?

### ISSUE THREAD

**Issue by whoiswct** [rdmrocha/linkalho#20]
Do linkalho 1.0.5 support switch os v.12.0?
I use atmosphere 0.19.1 in switch os12, and install linkalho 1.0.5. However, it seems not work properly with the game Let's sing 2021 which I would like to link with the mobile apps.

**Comment by rdmrocha** [comment]
Please re-read the description. This app ONLY creates a fake NNID Linked account. It will not allow you to connect to the internet or nintendo servers.
