### ISSUE TITLE
Not working on fw 12.x.x

### ISSUE THREAD

**Issue by Yeison017** [rdmrocha/linkalho#21]
Hello there, the app crashes on firmware 12.0.1 atmosphere 19.2, can you add support for 12.x.x?

**Comment by DerinQyu** [comment]
Try deleting your current files and intall linkalho again from scratch, make sure you create a folder named **linkalho** inside the **switch** folder then put the .nro file inside the linkalho folder.

Works for me on OFW 12.0.1 and both atmosphere 0.20.1 and 1.1.1

**Comment by rdmrocha** [comment]
v1.0.5 confirmed working today on 12.0.x, 12.1.0 and 13.0.0 with Atmosphere 1.1.1
