### ISSUE TITLE
Crash when linking accounts

### ISSUE THREAD

**Issue by Avasam** [rdmrocha/linkalho#27]
linkalho: v1.0.6
Atmosphère: 1.3.2
Firmware: 14.1.2

![IMG_20220801_123930469_HDR](https://user-images.githubusercontent.com/1350584/182200356-acd8479c-69c1-445b-b46d-df1c852a4fb2.jpg)

It seems it still linked the account.

**Comment by rdmrocha** [comment]
Tested on Atmos 1.3.2 + FW 14.1.2. Tested on a fresh install without any other modifications or atmosphere plugins.
