### ISSUE TITLE
v2.0.0 not linking account

### ISSUE THREAD

**Issue by pixeltester** [rdmrocha/linkalho#29]
v2.0.0 doesn't seem to work for me.

System: Erista, atmosphere 1.4.0 and firrmware 15.0.0. 1 account on system

Reproduce:
1. Unlink account with linkalho 1.0.6 and reboot
2. Open linkalho 2.0.0, check account which says "Not linked" and make sure it's selected
3. Exit to menu and select "Link selected accounts"

After rebooting and opening linkalho 2.0.0 account is still not linked.

**Comment by pixeltester** [comment]
Further testing: I can relink with v1.0.6 and reboot, v2.0.0 finds the account is linked but is also unable to unlink it. It seems like v2.0.0 won't link or unlink so far.

**Comment by DerinQyu** [comment]
Can confirm the same happens on my erista switch on 14.1.2 and atmosphere 1.4.0. 

1.0.6 still works to link/unlink

**Comment by rdmrocha** [comment]
If you can provide me a copy of your latest backup files in /switch/linkalho/backup (both linking and unlinking if any)

This update was developed using FW 14.2.1 with atmosphere 1.3.2. and tested in both the former and FW 15.0.0 with atmosphere 1.4.0 final

**Comment by DerinQyu** [comment]
> If you can provide me a copy of your latest backup files in /switch/linkalho/backup (both linking and unlinking if any)
> 
> This update was developed using FW 14.2.1 with atmosphere 1.3.2. and tested in both the former and FW 15.0.0 with atmosphere 1.4.0 final

[backup_profiles_20221021_131623[unlink].zip](https://github.com/rdmrocha/linkalho/files/9842269/backup_profiles_20221021_131623.unlink.zip)
[backup_profiles_20221021_131527[link].zip](https://github.com/rdmrocha/linkalho/files/9842270/backup_profiles_20221021_131527.link.zip)

Hello here are my backup files. Thank you for your time.

**Comment by rdmrocha** [comment]
@DerinQyu care to try this version and report back?

[linkalho-v2.0.1.zip](https://github.com/rdmrocha/linkalho/files/9842667/linkalho-v2.0.1.zip)

**Comment by DerinQyu** [comment]
> @DerinQyu care to try this version and report back?
> 
> [linkalho-v2.0.1.zip](https://github.com/rdmrocha/linkalho/files/9842667/linkalho-v2.0.1.zip)

hello, still not working for me
[backup_profiles_20221021_205016[link].zip](https://github.com/rdmrocha/linkalho/files/9843304/backup_profiles_20221021_205016.link.zip)
[backup_profiles_20221021_205149[unlink].zip](https://github.com/rdmrocha/linkalho/files/9843305/backup_profiles_20221021_205149.unlink.zip)

**Comment by rdmrocha** [comment]
@DerinQyu bug found. Please retest with this attached version just to double-check before I officially launch it

**Comment by rdmrocha** [comment]
> @DerinQyu bug found. Please retest with this attached version just to double-check before I officially launch it
> 
> [linkalho-v2.0.1.zip](https://github.com/rdmrocha/linkalho/files/9844166/linkalho-v2.0.1.zip)
> 
Reported working by two other people. Releasing it.

**Comment by DerinQyu** [comment]
Link and unlink are working great. Thank you so much.

**Comment by pixeltester** [comment]
That's fixed it for me too, thank you.
