### ISSUE TITLE
Localy change profile pictures

### ISSUE THREAD

**Issue by fennectech** [rdmrocha/linkalho#35]
Modifying the files in the aviators folder can change your user icon localy    ive tested and this does not sync over the internet

**Comment by rdmrocha** [comment]
You need to elaborate a bit more than that: first on what's the issue context, what's the expected behavior and what the current behavior is

**Comment by fennectech** [comment]
I’d like if we could use the application to replace an image in the aviators folder    You can do it manually by restoring a backup but if the tool could do it for you that would be awesome.   
![Uploading 7E74BD77-C86D-43A5-BF0E-A13090EF250D.jpeg…]()

**Comment by rdmrocha** [comment]
This is out of the scope for this application. 
Linkalho was created to link/unlink account, not to edit or manage profiles.
