### ISSUE TITLE
Linkalho is used to run some problematic games?

### ISSUE THREAD

**Issue by Marcusus57** [rdmrocha/linkalho#36]
Hello, i have a switch that has never had a Nintendo account activated, and Mario Strikers in NSP does not work, so when XCI works, does this mean that the game requires the presence of a Nintendo account?  I used your homebrew but it's the same problem with the NSP :/

**Comment by rdmrocha** [comment]
https://github.com/rdmrocha/linkalho#frequently-asked-questions
