### ISSUE TITLE
Accidentally Unlinked my main user account on Sysnand using Linkalho

### ISSUE THREAD

**Issue by zandurrr** [rdmrocha/linkalho#38]
Is there any way to recover my user profile? It is linked to my official Nintendo account before I accidentally unlinked it. Now I can't access the eshop, pokemon unite, and such with that user. I tried opening the root of the sd card and found the back up zip files in sd/switch/linkalho/backup and copy pasted it to the restore folder. However, upon booting the switch and opening the Linkalho app, it still can't detect any restoration files. Need help on this please, spent a lot of money on games in the eshop and pokemon unite. Also have a lot of save files on that main user account on Sysnand. Thanks

**Comment by impeeza** [comment]
Yes, restoring your backup. Please keep on mind this space is for bug report, for help please use corresponding spaces like discord or GBATemp
