### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by impeeza** [rdmrocha/linkalho#39]
Hello there I am trying to build Linkalho from source, I am using Linux Ubuntu and MSYS on Windows each time I try to run ```make``` I get the error:

```# make
Merging ROMFS...
rm: missing operand
Try 'rm --help' for more information.
make: *** [Makefile:180: resources] Error 123
```

looking on the Makefile you can see what the row 180 is:

`	@find . -name ".DS_Store" | xargs rm`

I guess what this line tries to remove a file which is not on the repo ".DS_Store", but the command on that line only works if the file exist, if the file do not exist trow an error and abort the make.

I think you should use another command like by example:

`	@[ -e .DS_Store ] && rm .DS_Store`

On this command the `rm` command is executed if the file do exist.

Thanks a lot for your work.

**Comment by rdmrocha** [comment]
@impeeza Your suggestion will not execute a recursive cleanup.
Pushed a change that should solve the issue
