### ISSUE TITLE
Restores Backup Users failed

### ISSUE THREAD

**Issue by Dikimgping** [rdmrocha/linkalho#40]
Hello, I have manually created from your app Linkahlo an Backup, this doesnt work because i put this backup zip on the folder of sdmc/switch/Linkahlo/Restore and it didnt work again, im from Germany, please fix this stuff men? 

Ofcourse i started the app on Linkahlo but, what i told you before it didnt work.

Thanks!

**Comment by rdmrocha** [comment]
Read the instructions on the GitHub page carefully: restore file needs to be copied AND renamed as `/switch/linkalho/restore/restore.zip`
