### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by sskyNS** [rdmrocha/linkalho#43]
```
linkalho/lib/borealis/library/include/borealis/actions.hpp:25:10: fatal error: G
LFW/glfw3.h: No such file or directory
   25 | #include <GLFW/glfw3.h>

```

**Comment by impeeza** [comment]
The borealis library needs to be upgraded to latest version from 

https://github.com/HamletDuFromage/borealis

even the latest version from RDMROCHA https://github.com/rdmrocha/borealis lacks of the latest changes to allow the build of the code.

**Comment by impeeza** [comment]
but your specific error indicate you haven't installed the package `switch-glfw`  in order to sucessfull build the code you need the packages:  `git make switch-glfw switch-mesa switch-glm switch-glad libnx switch-dev switch-zlib`
