### ISSUE TITLE
link only one account

### ISSUE THREAD

**Issue by chronoss09** [rdmrocha/linkalho#5]
I have 2 account on my Switch and i need to link only one, there is a solution to add a possibility to link only one account unstead of all account ?

Great job for this usefull app 😍

**Comment by Aliasim800** [comment]
Same here, I would also like this to be possible but you could always just link all 2 accounts and use a program like goldleaf to unlink an account if you need to.

**Comment by rdmrocha** [comment]
This feature is not going be implemented due to the extra complexity of the eventual cleanup process for previously linked accounts. If someone wants to contribute with a PR for it, I'll gladly review it and merged it into the app.
