### ISSUE TITLE
Reboot to payload fails if hbmenu is running in application mode

### ISSUE THREAD

**Issue by pixeltester** [rdmrocha/linkalho#6]
Atmosphere 0.14.4, firmware 10.2.0, linkalho v1.0.3

A bug I ran into: reboot to payload fails and the system reboots normally if hbmenu and linkalho are running in application mode (holding R and launching an application). In applet mode reboot to payload works normally.

Steps to reproduce: Launch hbmenu in application mode and load linkalho, create manual backup and choose to reboot.

**Comment by rdmrocha** [comment]
Did not test this scenario. Will take a look once I have time.

**Comment by rdmrocha** [comment]
Could not replicate. App reboots to payload fine using **Atmosphere 0.14.4, firmware 10.2.0, linkalho v1.0.3** as you described.
Went into **_application mode_** and rebooted fine to payload either by using fusee-primary or hekate (5.3.3).
I'd suggest you to check and update your current Atmosphere installation (pay special attention do `/atmosphere/reboot_payload.bin`)

**Comment by pixeltester** [comment]
I can assure you that my installation is 100% up to date. Perhaps a sysmodule is interfering which I'll investigate later.

It might have been a good idea to leave this open until the variable that's causing the issue is discovered. Regardless I'll comment here again when I've tested further.

**Comment by odEscOuT** [comment]
> I can assure you that my installation is 100% up to date. Perhaps a sysmodule is interfering which I'll investigate later.
> 
> It might have been a good idea to leave this open until the variable that's causing the issue is discovered. Regardless I'll comment here again when I've tested further.

Have you tried replacing the original reboot_payload.bin with the one from hekate and then trying again? (delete reboot_payload.bin and copy/paste the "payload".bin of hekate and rename it to reboot_payload.bin).
The issue that you mention should no longer take place with the latest release

**Comment by pixeltester** [comment]
I managed to resolve the issue by deactivating all sysmodules. After reactivating them one by one it seems it actually occurs when too many sysmodules are running rather than any specific sysmodule.

**Comment by rdmrocha** [comment]
> I managed to resolve the issue by deactivating all sysmodules. After reactivating them one by one it seems it actually occurs when too many sysmodules are running rather than any specific sysmodule.
> 
> This only occurs in linkalho as I can use reboot to payload with other apps that support it and my system is stable otherwise.

It is likely happening because this app needs to forcefully terminate some running processes so we can access the accounts and one your sysmodules might be crashing and/or triggering some unexpected behaviour because of this.
