### ISSUE TITLE
Failde！ filesystem error：recurslve diretory iterator cannot open directory:No such device [account:/su]

### ISSUE THREAD

**Issue by Sorata** [rdmrocha/linkalho#9]
Hello, I'm sorry to disturb you.

Is there any idea about this error?

SX Core - SX OS 3.0.5
Switch 10.2.0

Is Applet Mode insufficient authority?

**Comment by Sorata** [comment]
Hold down the R key and start a game, it will enter the high-privilege mode, and then try Linkalho.

**Comment by eyeonus** [comment]
Got the same error, was holding down R while starting ZeldaBOTW from its cart.
